version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_webhook
    expose:
      - "40871"  # Internal port
    restart: unless-stopped
    networks:
      - webnet

  nginx-proxy:
    image: nginx:latest
    container_name: nginx_webhook_proxy
    ports:
      - "40871:40871"  # Map external to internal
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - fastapi-app
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
